### PR TITLE
Docs: Team Permission: Add a note about the app rights

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Review by gsmet — CHANGES_REQUESTED** [review]
I suggested some adjustments. Can you check it's what you had in mind when writing this note?

If so, I will squash and merge, thanks!

**Comment by radtriste** [comment]
@gsmet much better :)

**Review by gsmet — APPROVED** [review]
Thanks for taking the time to contribute to the doc!

**Comment by gsmet** [comment]
@radtriste I'm curious, what are you working on? :)

**Comment by radtriste** [comment]
> @radtriste I'm curious, what are you working on? :)

A bot for Kogito (and other KIE projects): https://github.com/kiegroup/kiebot

**Pull request merged**
