### PR TITLE
Allow the webhook listener path to be configurable

### LINKED ISSUE #629: Allow Github Event ruoting to serve on HTTP Paths other than root
Currently, this extension listens for GitHub Events on the root path of the HTTP server. This is expressed in two locaitons that I'm aware of 
- the Vertx route registration: https://github.com/quarkiverse/quarkus-github-app/blob/main/runtime/src/main/java/io/quarkiverse/githubapp/runtime/Routes.java#L75C1-L75C141
- The Smee forwarder: https://github.com/quarkiverse/quarkus-github-app/blob/main/runtime/src/main/java/io/quarkiverse/githubapp/runtime/smee/SmeeIoForwarder.java#L53

I would like to serve this listener from my application which is a GitHub app but also serves other HTTP requests, and the root path of the application is already spoken for. Ideally, i'd like to configure this extension to listen on `/github-event`, which is where my own GitHub event routing listens currently, but i think it's sensible to allow for any path to be configured. I think this will help those who would like to migrate to this extension an easier path to do so because they may not follow the conventions laid out in this extension.

The `Routes` class would have to programmatically register the route via an injected vertx router rather than via the `@Route` annotation, but it seems relatively straightforward.

If you're open to the change, I'd be happy to make a PR to contribute it.

### PR DESCRIPTION
**Pull request by ryandens**
Fixes #629

- Defaults to what was hardcoded previously `/`

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
@ryandens I added two more commits with some small adjustments.

Let me know if it's all good for you and I'll merge.

**Comment by gsmet** [comment]
Thanks!

**Comment by gsmet** [comment]
@ryandens I released 2.6.0 which includes your 2 contributions.

**Comment by ryandens** [comment]
Amazing, thank you @gsmet! We were already using aspects of this extension to build [pixeebot](https://github.com/marketplace/pixeebot-automated-code-fixes (like the `GitHubClientProvider` and the `PayloadSignatureChecker` but now we'll be able to use more aspects of it 😄 Looking forward to making more contributions along the way

**Pull request merged**
