### PR TITLE
Use quarkus-smallrye-jwt-build to generate JWT

### LINKED ISSUE #55: Once Quarkus 1.11 is released, use quarkus-smallrye-jwt-build
```
public String createJwtToken(String githubAppId, PrivateKey privateKey, long ttlMillis)
            throws GeneralSecurityException, IOException {
       // RS256 is default
       // issued at is set to default to now()
       return Jwt.issuer(githubAppId).expiresAt(ttlMillis).sign(privateKey);
```

### PR DESCRIPTION
**Pull request by jtama**
Fixes #55

### CODE REVIEW

**Comment by jtama** [comment]
Downstream tests are failing, but I can't see why this change should break those tests

**Comment by gsmet** [comment]
@jtama yes, no worries, the Hibernate one are broken for another reason.

**Comment by gsmet** [comment]
Let me test that in native and I will merge.

**Review by gsmet — APPROVED** [review]
It's working well in native too, thanks!

I cleaned up the parent pom from the unused dependencies.

**Pull request merged**
